oauthagent:
  clientID: spa-client
  redirectUri: https://www.example.local/
  postLogoutRedirectURI: https://www.example.local/
  scope: openid profile

  financialGrade: true

  encKey: 4e4636356d65563e4c73233847503e3b21436e6f7629724950526f4b5e2e4e50
  cookieNamePrefix: example
  endpointsPrefix: 'oauth-agent'
  cookieSerializeOptions:
    httpOnly: true
    sameSite: true
    secure: true
    domain: api.example.local
    path: '/'

  trustedWebOrigins:
  - https://www.example.local
  corsEnabled: true
  issuer: https://login.example.local:8443/oauth/v2/oauth-anonymous
  jwksUri: https://login.example.local:8443/oauth/v2/oauth-anonymous/jwks
  authorizeEndpoint: https://login.example.local:8443/oauth/v2/oauth-authorize
  authorizeExternalEndpoint: https://login.example.local:8443/oauth/v2/oauth-authorize
  logoutEndpoint: https://login.example.local:8443/oauth/v2/oauth-session/logout
  tokenEndpoint: https://login.example.local:8443/oauth/v2/oauth-token
  userInfoEndpoint: https://login.example.local:8443/oauth/v2/oauth-userinfo

  ssl:
    enabled: true
    key-store: ./certs/example.client.p12
    key-store-password: Password1
    trust-store: ./certs/example.ca.pem

server:
  port: 8080
  ssl:
    enabled: true
    key-store: ./certs/example.server.p12
    key-store-password: Password1