oauthagent:
  clientID: ${CLIENT_ID:spa-client}
  redirectUri: ${REDIRECT_URI:https://www.example.local/}
  postLogoutRedirectURI: ${POST_LOGOUT_REDIRECT_URI:https://www.example.local/}
  scope: ${SCOPE:openid profile}

  financialGrade: ${FINANCIAL_GRADE:true}

  encKey: ${COOKIE_ENCRYPTION_KEY:4e4636356d65563e4c73233847503e3b21436e6f7629724950526f4b5e2e4e50}
  cookieNamePrefix: ${COOKIE_NAME_PREFIX:example}
  endpointsPrefix: 'oauth-agent'
  cookieSerializeOptions:
    httpOnly: true
    sameSite: true
    secure: true
    domain: ${COOKIE_DOMAIN:api.example.local}
    path: '/'

  trustedWebOrigins:
  - ${TRUSTED_WEB_ORIGIN:https://www.example.local}
  corsEnabled: ${CORS_ENABLED:true}
  issuer: ${ISSUER:https://login.example.local:8443/oauth/v2/oauth-anonymous}
  jwksUri: ${JWKS_URI:https://login.example.local:8443/oauth/v2/oauth-anonymous/jwks}
  authorizeEndpoint: ${AUTHORIZE_ENDPOINT:https://login.example.local:8443/oauth/v2/oauth-authorize}
  authorizeExternalEndpoint: ${AUTHORIZE_EXTERNAL_ENDPOINT:https://login.example.local:8443/oauth/v2/oauth-authorize}
  logoutEndpoint: ${LOGOUT_ENDPOINT:https://login.example.local:8443/oauth/v2/oauth-session/logout}
  tokenEndpoint: ${TOKEN_ENDPOINT:https://login.example.local:8443/oauth/v2/oauth-token}
  userInfoEndpoint: ${USERINFO_ENDPOINT:https://login.example.local:8443/oauth/v2/oauth-userinfo}

  ssl:
    key-store: ${CLIENT_CERT_P12_PATH:./certs/example.client.p12}
    key-store-password: ${CLIENT_CERT_P12_PASSWORD:Password1}
    trust-store: ${CA_CERT_PEM_PATH:./certs/example.ca.pem}

server:
  port: ${PORT:8080}
  ssl:
    key-store: ${SERVER_CERT_P12_PATH:./certs/example.server.p12}
    key-store-password: ${SERVER_CERT_P12_PASSWORD:Password1}