bff:
  clientID: 'spa-client'
  redirectUri: 'http://www.example.com/'
  postLogoutRedirectURI: 'http://www.example.com/'
  scope: 'openid profile'

  encKey: 'NF65meV>Ls#8GP>;!Cnov)rIPRoK^.NP'
  salt: 'NF62meS>Ls%83P>;!Cdfv)rHTRoK!F)P'
  cookieNamePrefix: 'example'
  bffEndpointsPrefix: 'bff'
  cookieSerializeOptions:
    httpOnly: true
    sameSite: true
    secure: false
    domain: '.example.com'
    path: '/'

  trustedWebOrigins: [ 'http://www.example.com' ]
  issuer: 'https://login.example.com:8443/oauth/v2/oauth-anonymous'
  jwksUri: 'https://login.example.com:8443/oauth/v2/oauth-anonymous/jwks'
  authorizeEndpoint: 'https://login.example.com:8443/oauth/v2/oauth-authorize'
  logoutEndpoint: 'https://login.example.com:8443/oauth/v2/oauth-session/logout'
  tokenEndpoint: 'https://login.example.com:8443/oauth/v2/oauth-token'

  ssl:
    key-store: bff-kotlin-client.p12
    key-store-password: Secr3t
    trust-store: idsvr.p12
    trust-store-password: Secr3t
